### ISSUE TITLE
missing cash.sh?

### ISSUE THREAD

**Issue by JeremyVV** [khailey/wash#1]
The README.md indicates that cash.sh should be run however it is missing in the latest version.  Is this deliberate?

**Comment by khailey-zz** [comment]
not sure what happened - just re-added
Haven't looked at this code in while - last commit was 4 years ago
been meaning to revisit - I recall that it could some improvements around choosing the database to be monitored, as this is embeded in the URL and not user friendly

**Comment by JeremyVV** [comment]
Thank you for the info and quick response.
